language: java
env:
  global:
    - CATALINA_PID=/tmp/tomcat.pid
    - CATALINA_OUT=/tmp/tomcat.log
before_install:
  - git pull --unshallow
  - wget -O tomcat.tar.gz http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.52/bin/apache-tomcat-7.0.52.tar.gz
install: 
  - mvn -U clean --quiet -DskipTests=true
  - mvn -U install --quiet -DskipTests=true
  - mkdir -p target/tomcat && tar zxf tomcat.tar.gz -C target/tomcat --strip-components 1 && rm -rf target/tomcat/webapps/*
  - UAA_VERSION=`mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=identity.version | grep -v "[\\[|Download]"`
  - mvn dependency:get -pl login-server -Dartifact=org.cloudfoundry.identity:cloudfoundry-identity-uaa:$UAA_VERSION
  - cp $HOME/.m2/repository/org/cloudfoundry/identity/cloudfoundry-identity-uaa/$UAA_VERSION/cloudfoundry-identity-uaa-$UAA_VERSION.war target/tomcat/webapps/uaa.war
  - mvn -Dwar.exploded.dir=`pwd`/target/tomcat/webapps/login --quiet -pl login-server war:exploded
script: 
  - ./.run-script.sh start
  - mvn -Dtest=org.cloudfoundry.identity.uaa.integration.* -DfailIfNoTests=false test --quiet
  - cd login-server-integration-tests && mvn verify --quiet
  - cd $TRAVIS_BUILD_DIR
  - ./.run-script.sh stop
  - mvn -Dspring.profiles.active=$TESTENV test --quiet
after_failure:
  - cat $CATALINA_OUT
after_script:
  - rm -rf tomcat
  - rm -f tomcat.tar.gz
