language: java
before_install: 
  - mvn -v
  - git pull --unshallow
install: 
  -  mvn -U clean --quiet -DskipTests=true
  -  mvn -U install --quiet -DskipTests=true
script: 
  - ./.run-script.sh
  - mvn test
  - cd login-server-integration-tests && mvn verify
  - cd $TRAVIS_BUILD_DIR
  - kill -9 `cat mvn.pid`
  - rm -f mvn.pid
