language: java
env:
  global:
    - CATALINA_PID=/tmp/tomcat.pid
    - CATALINA_OUT=/tmp/tomcat.log
    - CATALINA_OPTS="-XX:MaxPermSize=256M -DUAA_PROFILE=local"
    - secure: "aBHaT7agd8Cliz+JMvgqt3+FbixdW/nw2u2ttZBb/AR+fhTemNRRapQDZ6nFKhdQtbzR3nUH8HLksvZhuX9u3L1eGkGP1dB3wEoIXeqO7FP2OcR5iiJ9wan+QFv4JTfhdS1DMhkv5z8HS2vCGvstUYhjUJRdmvp8hmbaLDYm0bo="
  matrix:
    - SPRING_PROFILES=default,coverage
    - SPRING_PROFILES=default,saml,coverage
before_install:
  - git pull --unshallow
  - wget -O tomcat.tar.gz http://archive.apache.org/dist/tomcat/tomcat-7/v7.0.52/bin/apache-tomcat-7.0.52.tar.gz
install:
  - cd $TRAVIS_BUILD_DIR/uaa
  - mvn install -DskipTests --quiet
  - cd $TRAVIS_BUILD_DIR
  - $TRAVIS_BUILD_DIR/.apply_spring_profiles_to_login_yaml.sh $SPRING_PROFILES
  - cat src/main/resources/login.yml
  - mvn test-compile -P coverage --quiet
  - mkdir -p target/tomcat
  - tar zxf tomcat.tar.gz -C target/tomcat --strip-components 1
  - export WEBAPPS_DIR=$TRAVIS_BUILD_DIR/target/tomcat/webapps
  - rm -rf $WEBAPPS_DIR/*
  - export IDENTITY_VERSION=`mvn help:evaluate -Dexpression=project.parent.version | grep -v "\[" | tail -n 1`
  - mv $TRAVIS_BUILD_DIR/uaa/uaa/target/cloudfoundry-identity-uaa-*.war $WEBAPPS_DIR/uaa.war
  - mv $TRAVIS_BUILD_DIR/uaa/samples/app/target/cloudfoundry-identity-app-*.war $WEBAPPS_DIR/app.war
  - mv $TRAVIS_BUILD_DIR/uaa/samples/api/target/cloudfoundry-identity-api-*.war $WEBAPPS_DIR/api.war
before_script:
  - $TRAVIS_BUILD_DIR/.cobertura-instrument.sh
  - mvn -Dwar.exploded.dir=$WEBAPPS_DIR/login war:exploded -P coverage
  - export CI_LOGGING_CONFIG=$TRAVIS_BUILD_DIR/src/test/resources/log4j_ci.properties
script:
  - ./.run-script.sh start
  - mvn -Dspring.profiles.active=${SPRING_PROFILES} -Dlogging.config=file://$CI_LOGGING_CONFIG -Dlog4j.configuration=$CI_LOGGING_CONFIG verify -DforceIntegrationTests -DfailIfNoTests=false -Dtest="org.cloudfoundry.identity.uaa.login.feature.*" -P coverage
  - curl -v -X POST http://localhost:8080/login/healthz/coverage/flush
  - ./.run-script.sh stop
  - mvn -Dspring.profiles.active=${SPRING_PROFILES} -Dlogging.config=file://$CI_LOGGING_CONFIG -Dlog4j.configuration=$CI_LOGGING_CONFIG test -P coverage
after_success:
  - $TRAVIS_BUILD_DIR/.cobertura-report.sh
  - mvn coveralls:cobertura
  - python scripts/travis/travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_succeeded" ]; then
          echo "All Succeded!"
          if [ "$TRAVIS_BRANCH" = "develop" ]; then
            $TRAVIS_BUILD_DIR/scripts/travis/auto-bump-uaa.sh
          fi
        else
          echo "Some Failed"
        fi
      fi
after_failure:
  - python scripts/travis/travis_after_all.py
  - export $(cat .to_export_back)
  - |
      if [ "$BUILD_LEADER" = "YES" ]; then
        if [ "$BUILD_AGGREGATE_STATUS" = "others_failed" ]; then
          echo "All Failed"
        else
          echo "Some Failed"
        fi
      fi
  - cat $CATALINA_OUT
after_script:
  - echo leader=$BUILD_LEADER status=$BUILD_AGGREGATE_STATUS